### ISSUE TITLE
Refactor task list

### ISSUE THREAD

**Issue by flashadvocate** [flashadvocate/Division-Tracker#49]
## Primary
- [x] Backend, build out models, classes, sparrow and flight framework support 
- [x] Home view for admin, plt ldrs, squad leaders, users
- [x] Division view
- [x] Platoon view
- [x] Member view
  - [x] Member profile
  - [x] Edit member
  - [x] Update member
- [x] Recruiting Tool
  - [x] validate member (for aod membership)
  - [x] check recruitment threads per division for player post
  - [x] validate battlelog name (to ensure it exists, and we can get a battlelog id for stats)
  - [x] create member upon recruitment completion
- [x] Division structure generator
- [x] Manage LOAs
- [x] Manage Inactives
- [x] Account creation
- [x] Forum arch synchro cron

## Secondary
- [x] Integrate battlelog to replace bf4 activity cron
- [x] Implement BFH activity cron
- [ ] Add (bf4) (bfh) game indicator to division structure, member view (ref: https://github.com/flashadvocate/Division-Tracker/issues/10#issuecomment-90961825)

## Tertiary
- [x] Toplist images / PHP GD
- [ ] Add platoon
- [ ] Add division
- [ ] Squad view
